const rolePermissions = {
  super_admin: [
    "manage_users",
    "view_users",
    "view_clients",
    "manage_clients",
    "delete_clients",
    "view_projects",
    "manage_projects",
    "delete_projects",
    "view_tasks",
    "manage_tasks",
    "update_task_status",
    "delete_tasks",
    "generate_ai",
    "view_dashboard",
    "view_platforms",
    "manage_platforms",
    "view_earnings",
    "manage_payments",
    "view_leads",
    "manage_leads",
  ],

  admin: [
    "manage_users",
    "view_users",
    "view_clients",
    "manage_clients",
    "delete_clients",
    "view_projects",
    "manage_projects",
    "delete_projects",
    "view_tasks",
    "manage_tasks",
    "update_task_status",
    "delete_tasks",
    "generate_ai",
    "view_dashboard",
    "view_platforms",
    "manage_platforms",
    "view_earnings",
    "manage_payments",
    "view_leads",
    "manage_leads",
  ],

  manager: [
    "view_users",
    "view_clients",
    "manage_clients",
    "view_projects",
    "manage_projects",
    "view_tasks",
    "manage_tasks",
    "update_task_status",
    "generate_ai",
    "view_dashboard",
    "view_platforms",
    "view_earnings",
    "view_leads",
    "manage_leads",
  ],

  developer: [
    "view_projects",
    "view_tasks",
    "update_task_status",
    "view_dashboard",
    "view_platforms",
  ],

  client: [
    "view_own_projects",
    "view_own_tasks",
  ],
};

module.exports = rolePermissions;
